server:
  port: 8084
spring:
  profiles:
    active: real
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://syh80882.cafe24.com/syh80882
    driverClassName: com.mysql.jdbc.Driver
    username: syh80882
    password: abc123!@
    sql-script-encoding: utf-8
  messages:
    basename: messages/messages, messages/error
  jpa:
    show-sql: true

  redis:
    host: localhost
    port: 6379
  #profiles:
  #  active: local


mybatis:
  type-aliases-package: com.example.api
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
debug: true
logging:
  level:
    org.springframework: debug


healthCheckMessage: default

management:
  port: 18081
  security:
    roles: ADMIN

#jasypt:
#  encryptor:
#    bean: jasyptStringEncryptor

naver:
  client:
    clientId: ZYywOLuKwRvc5jHguZy4
    clientSecret: 9I1vFrLO9R
    accessTokenUri: https://nid.naver.com/oauth2.0/token
    userAuthorizationUri: https://nid.naver.com/oauth2.0/authorize
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://openapi.naver.com/v1/nid/me

google:
  client:
    clientId: 475081898784-vu924jjrnnfcn2tm7n9v9fla529rvr2q.apps.googleusercontent.com
    clientSecret: pH0pOP8rBI2oBT2YoZY9_v6K
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    clientAuthenticationScheme: form
    scope: email, profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo


---

spring:
  profiles: real
healthCheckMessage: real